### ISSUE TITLE
A potential bug of null pointer dereference

### ISSUE THREAD

**Issue by ash1852** [bfredl/pangoterm#2]
hello, I found a potential bug of null-pointer-dereference in source code of pangoterm,could you help me check if this bug is true?thank you very much.

the overview of occurrence of the bug is shown as follow:
<img width="840" alt="3" src="https://user-images.githubusercontent.com/87304478/145370319-ae642c9a-56e0-4af2-803b-fcd5d99a1e88.png">
step1:
in file pangoterm/conf.c , [line 241](https://github.com/bfredl/pangoterm/blob/mein/conf.c#L241), call g_strdup
step2:
in file glib2.0-2.56.4/glib/gstrfuncs.c , line 360. select the false branch,which means str == null
step3:
in file glib2.0-2.56.4/glib/gstrfuncs.c , line 367. load null to new_str
step4:
in file glib2.0-2.56.4/glib/gstrfuncs.c , line 369. return new_str(null)
step5:
in file pangoterm/conf.c , [line 241](https://github.com/bfredl/pangoterm/blob/mein/conf.c#L241), load return value of g_strdup to longname
step6:
in file pangoterm/conf.c , [line 244](https://github.com/bfredl/pangoterm/blob/mein/conf.c#L244)---[line 246](https://github.com/bfredl/pangoterm/blob/mein/conf.c#L246),derefer longname(s) here without check if longname(s) is null.

**Comment by ash1852** [comment]
would you give me a reason where closed this issue? Is this bug is false? Looking forward to your reply.Thanks.

**Comment by bfredl** [comment]
It's spam. Just autogenerated from some scan-build tool with no understanding of the code itself.

**Comment by ash1852** [comment]
thank you.
